# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "./bin/erabooru"
  cmd = "make backend-build"
  delay = 1000 # ms
  exclude_dir = ["bin", "assets", "tmp", "vendor", "internal/assets", "ent", "web/node_modules", "web/build"]
  exclude_file = []
  exclude_regex = [".*_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = ["web/src"]
  include_ext = ["go", "toml", "yaml", "yml", "html", "svelte", "js", "ts", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true