# docker-compose.pull.yml
services:
  app:
    image: ghcr.io/era-things/erabooru-api:latest
    build: null       
    env_file:          
      - .env
    depends_on:        
      db:
        condition: service_healthy
      minio:
        condition: service_started
      caddy:
        condition: service_started
      bleve-init:
        condition: service_completed_successfully
    volumes:
      - ./bleve-index:/data/bleve

  video-worker:
    image: ghcr.io/era-things/erabooru-video:latest
    build: null

  caddy:
    ports:
      - "80:80"