services:
  app:
    image: booru:dev
    build:
      context: .
      target: dev
    command: ./scripts/dev.sh
    volumes:
      - .:/app
      - ./bleve-index:${BLEVE_PATH}
    ports:
      - "5173:5173"
      - "8080:8080"
    depends_on:
      - db
      - minio
      - caddy
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    command: --bind=0.0.0.0 --listen=8081 --url postgres://booru:booru@db:5432/booru?sslmode=disable
    depends_on:
      - db