# docker-compose.prod.yml – only the diffs from the base file
services:
  app:
    image: ghcr.io/era-things/erabooru-api:latest
    build: null       
    volumes:
      - ./bleve-index:/data/bleve     # named vol so any path works

  video-worker:
    image: ghcr.io/era-things/erabooru-video:latest
    build: null

  caddy:
    ports:
      - "80:80"        # publish only the HTTP port; TLS later
