services:
  app:
    build:
      context: .
      target: dev
    command: ./scripts/dev.sh
    volumes:
      - .:/app
    ports:
      - "5173:5173"
      - "8080:8080"
    depends_on:
      - db
      - minio
      - caddy

