# docker-compose.pull.yml
services:
  app:
    image: ghcr.io/era-things/erabooru-api:latest
    build: null       
    volumes:
      - ./bleve-index:/data/bleve

  media-worker:
    image: ghcr.io/era-things/erabooru-media:latest
    build: null

  caddy:
    ports:
      - "80:80"