swagger: "2.0"
info:
    title: Erabooru API
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/admin/regenerate:
        post:
            tags:
                - admin
            summary: regenerate admin
            description: Regenerate search index and metadata
            operationId: admin#regenerate
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /api/media:
        get:
            tags:
                - media
            summary: list media
            description: List media items
            operationId: media#list
            parameters:
                - name: q
                  in: query
                  required: false
                  type: string
                - name: page
                  in: query
                  required: false
                  type: integer
                - name: page_size
                  in: query
                  required: false
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/MediaList'
                        required:
                            - media
                            - total
            schemes:
                - http
    /api/media/{id}:
        get:
            tags:
                - media
            summary: get media
            description: Get media item by ID
            operationId: media#get
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/MediaDetail'
            schemes:
                - http
        delete:
            tags:
                - media
            summary: delete media
            description: Delete media item
            operationId: media#delete
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /api/media/{id}/tags:
        post:
            tags:
                - media
            summary: updateTags media
            description: Update tags for media item
            operationId: media#updateTags
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        tags:
                            type: array
                            items:
                                type: string
                                example: Magni minus odit voluptate aspernatur consequatur.
                            example:
                                - Dolore nihil qui labore occaecati.
                                - Et aut qui provident vitae ipsam quia.
                                - Eius iusto quo quas provident.
                                - Eos eos.
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /api/media/previews:
        get:
            tags:
                - media
            summary: previews media
            description: List media previews
            operationId: media#previews
            parameters:
                - name: q
                  in: query
                  required: false
                  type: string
                - name: page
                  in: query
                  required: false
                  type: integer
                - name: page_size
                  in: query
                  required: false
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/MediaList'
                        required:
                            - media
                            - total
            schemes:
                - http
    /api/media/upload-url:
        post:
            tags:
                - media
            summary: uploadURL media
            description: Get a presigned upload URL
            operationId: media#uploadURL
            parameters:
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        filename:
                            type: string
                            example: Voluptates omnis dolores iste fuga cum.
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UploadURLResponse'
            schemes:
                - http
    /health:
        get:
            tags:
                - health
            summary: check health
            operationId: health#check
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
definitions:
    MediaDetail:
        title: MediaDetail
        type: object
        properties:
            duration:
                type: integer
                description: Video duration in seconds
                example: 6407544713652780994
                format: int64
            format:
                type: string
                example: In ipsum expedita laboriosam quis voluptatibus.
            height:
                type: integer
                example: 5297256562421773894
                format: int64
            id:
                type: string
                example: Sint facilis qui autem architecto ratione sit.
            size:
                type: integer
                example: 3802429833670727526
                format: int64
            tags:
                type: array
                items:
                    type: string
                    example: Voluptas quo.
                example:
                    - Consequatur sequi voluptas.
                    - Consequatur repellendus maxime et qui cum.
                    - Laboriosam illo repellat reprehenderit ducimus magni architecto.
                    - Laboriosam dolorem aut omnis eos totam eum.
            url:
                type: string
                example: Illo quidem est labore accusantium.
            width:
                type: integer
                example: 8243442555000497719
                format: int64
        example:
            duration: 8598132828851712949
            format: Porro corporis earum ipsam omnis repellat doloremque.
            height: 4552100772837244467
            id: Aut et occaecati dolores sit est beatae.
            size: 8920198679462767624
            tags:
                - Eum sed.
                - Modi est optio.
                - Mollitia voluptatem doloremque earum saepe.
            url: Id enim optio vel aut.
            width: 8518428931102910048
    MediaItem:
        title: MediaItem
        type: object
        properties:
            format:
                type: string
                example: Magnam expedita ipsum voluptatibus et eum aut.
            height:
                type: integer
                example: 5306399066195182777
                format: int64
            id:
                type: string
                example: Eos dicta aperiam commodi dolor non.
            url:
                type: string
                example: Et facilis dicta.
            width:
                type: integer
                example: 2573868345166883389
                format: int64
        example:
            format: Ipsum odio adipisci rerum esse qui voluptate.
            height: 5913083685881163311
            id: Minima maiores numquam qui velit delectus et.
            url: Eos distinctio perferendis.
            width: 2068459752071381447
    MediaList:
        title: MediaList
        type: object
        properties:
            media:
                type: array
                items:
                    $ref: '#/definitions/MediaItem'
                example:
                    - format: Ea voluptate qui delectus rerum.
                      height: 4478699467164243213
                      id: Iusto culpa ex repellat est maiores.
                      url: Laboriosam aut recusandae.
                      width: 4269257746853478508
                    - format: Ea voluptate qui delectus rerum.
                      height: 4478699467164243213
                      id: Iusto culpa ex repellat est maiores.
                      url: Laboriosam aut recusandae.
                      width: 4269257746853478508
                    - format: Ea voluptate qui delectus rerum.
                      height: 4478699467164243213
                      id: Iusto culpa ex repellat est maiores.
                      url: Laboriosam aut recusandae.
                      width: 4269257746853478508
            total:
                type: integer
                example: 7695749859172376738
                format: int64
        example:
            media:
                - format: Ea voluptate qui delectus rerum.
                  height: 4478699467164243213
                  id: Iusto culpa ex repellat est maiores.
                  url: Laboriosam aut recusandae.
                  width: 4269257746853478508
                - format: Ea voluptate qui delectus rerum.
                  height: 4478699467164243213
                  id: Iusto culpa ex repellat est maiores.
                  url: Laboriosam aut recusandae.
                  width: 4269257746853478508
            total: 4688042499977521556
        required:
            - media
            - total
    UploadURLResponse:
        title: UploadURLResponse
        type: object
        properties:
            object:
                type: string
                example: Laboriosam cumque vel est.
            url:
                type: string
                example: Magni minus blanditiis corporis accusamus.
        example:
            object: Alias optio labore quo tempore aut aperiam.
            url: Earum doloribus numquam odio ratione qui.
